[package]
name = "cwe-client-cli"
version = "1.0.0"
description = "Desktop CLI client for cwe"
authors = ["icelayer"]
license = "GPL-3.0+"
repository = "https://github.com/NotBalds/cwe-client-cli"
default-run = "cwe-client-cli"
edition = "2021"
rust-version = "1.78"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
directories = "5.0.1"
once_cell = "1.20.3"
notblib = "0.2.1"
